# -*- coding: utf-8 -*-
#
# Copyright (c) ZeroC, Inc. All rights reserved.
#
#
# Ice version 3.7.11
#
# <auto-generated>
#
# Generated from file `Printer.ice'
#
# Warning: do not edit this file.
#
# </auto-generated>
#

from sys import version_info as _version_info_
import Ice, IcePy

# Start of module Demo
_M_Demo = Ice.openModule('Demo')
__name__ = 'Demo'

# ---- Interface Printer ----

_M_Demo._t_Printer = IcePy.defineValue('::Demo::Printer', Ice.Value, -1, (), False, True, None, ())

if 'PrinterPrx' not in _M_Demo.__dict__:
    _M_Demo.PrinterPrx = Ice.createTempClass()
    class PrinterPrx(Ice.ObjectPrx):

        def printString(self, s, context=None):
            return _M_Demo.Printer._op_printString.invoke(self, ((s, ), context))

        def printStringAsync(self, s, context=None):
            return _M_Demo.Printer._op_printString.invokeAsync(self, ((s, ), context))

        def begin_printString(self, s, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.Printer._op_printString.begin(self, ((s, ), _response, _ex, _sent, context))

        def end_printString(self, _r):
            return _M_Demo.Printer._op_printString.end(self, _r)

        # NOVO: inverte a string
        def printReversed(self, s, context=None):
            return _M_Demo.Printer._op_printReversed.invoke(self, ((s, ), context))

        def printReversedAsync(self, s, context=None):
            return _M_Demo.Printer._op_printReversed.invokeAsync(self, ((s, ), context))

        def begin_printReversed(self, s, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.Printer._op_printReversed.begin(self, ((s, ), _response, _ex, _sent, context))

        def end_printReversed(self, _r):
            return _M_Demo.Printer._op_printReversed.end(self, _r)

        # NOVO: repete a string n vezes
        def repeatString(self, s, n, context=None):
            return _M_Demo.Printer._op_repeatString.invoke(self, ((s, n), context))

        def repeatStringAsync(self, s, n, context=None):
            return _M_Demo.Printer._op_repeatString.invokeAsync(self, ((s, n), context))

        def begin_repeatString(self, s, n, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.Printer._op_repeatString.begin(self, ((s, n), _response, _ex, _sent, context))

        def end_repeatString(self, _r):
            return _M_Demo.Printer._op_repeatString.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Demo.PrinterPrx.ice_checkedCast(proxy, '::Demo::Printer', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Demo.PrinterPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Demo::Printer'

    _M_Demo._t_PrinterPrx = IcePy.defineProxy('::Demo::Printer', PrinterPrx)
    _M_Demo.PrinterPrx = PrinterPrx
    del PrinterPrx

    _M_Demo.Printer = Ice.createTempClass()
    class Printer(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Demo::Printer', '::Ice::Object')

        def ice_id(self, current=None):
            return '::Demo::Printer'

        @staticmethod
        def ice_staticId():
            return '::Demo::Printer'

        def printString(self, s, current=None):
            raise NotImplementedError("servant method 'printString' not implemented")

        def printReversed(self, s, current=None):
            raise NotImplementedError("servant method 'printReversed' not implemented")

        def repeatString(self, s, n, current=None):
            raise NotImplementedError("servant method 'repeatString' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Demo._t_PrinterDisp)

        __repr__ = __str__

    _M_Demo._t_PrinterDisp = IcePy.defineClass('::Demo::Printer', Printer, (), None, ())
    Printer._ice_type = _M_Demo._t_PrinterDisp

    Printer._op_printString = IcePy.Operation('printString', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_string, False, 0), ())
    Printer._op_printReversed = IcePy.Operation('printReversed', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0),), (), ((), IcePy._t_string, False, 0), ())
    Printer._op_repeatString = IcePy.Operation('repeatString', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_string, False, 0), ((), IcePy._t_int, False, 0)), (), ((), IcePy._t_string, False, 0), ())

    _M_Demo.Printer = Printer
    del Printer

# ---- Interface TemperatureConverter ----

_M_Demo._t_TemperatureConverter = IcePy.defineValue('::Demo::TemperatureConverter', Ice.Value, -1, (), False, True, None, ())

if 'TemperatureConverterPrx' not in _M_Demo.__dict__:
    _M_Demo.TemperatureConverterPrx = Ice.createTempClass()
    class TemperatureConverterPrx(Ice.ObjectPrx):

        def celsiusToFahrenheit(self, celsius, context=None):
            return _M_Demo.TemperatureConverter._op_celsiusToFahrenheit.invoke(self, ((celsius, ), context))

        def celsiusToFahrenheitAsync(self, celsius, context=None):
            return _M_Demo.TemperatureConverter._op_celsiusToFahrenheit.invokeAsync(self, ((celsius, ), context))

        def begin_celsiusToFahrenheit(self, celsius, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.TemperatureConverter._op_celsiusToFahrenheit.begin(self, ((celsius, ), _response, _ex, _sent, context))

        def end_celsiusToFahrenheit(self, _r):
            return _M_Demo.TemperatureConverter._op_celsiusToFahrenheit.end(self, _r)

        def fahrenheitToCelsius(self, fahrenheit, context=None):
            return _M_Demo.TemperatureConverter._op_fahrenheitToCelsius.invoke(self, ((fahrenheit, ), context))

        def fahrenheitToCelsiusAsync(self, fahrenheit, context=None):
            return _M_Demo.TemperatureConverter._op_fahrenheitToCelsius.invokeAsync(self, ((fahrenheit, ), context))

        def begin_fahrenheitToCelsius(self, fahrenheit, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.TemperatureConverter._op_fahrenheitToCelsius.begin(self, ((fahrenheit, ), _response, _ex, _sent, context))

        def end_fahrenheitToCelsius(self, _r):
            return _M_Demo.TemperatureConverter._op_fahrenheitToCelsius.end(self, _r)

        def celsiusToKelvin(self, celsius, context=None):
            return _M_Demo.TemperatureConverter._op_celsiusToKelvin.invoke(self, ((celsius, ), context))

        def celsiusToKelvinAsync(self, celsius, context=None):
            return _M_Demo.TemperatureConverter._op_celsiusToKelvin.invokeAsync(self, ((celsius, ), context))

        def begin_celsiusToKelvin(self, celsius, _response=None, _ex=None, _sent=None, context=None):
            return _M_Demo.TemperatureConverter._op_celsiusToKelvin.begin(self, ((celsius, ), _response, _ex, _sent, context))

        def end_celsiusToKelvin(self, _r):
            return _M_Demo.TemperatureConverter._op_celsiusToKelvin.end(self, _r)

        @staticmethod
        def checkedCast(proxy, facetOrContext=None, context=None):
            return _M_Demo.TemperatureConverterPrx.ice_checkedCast(proxy, '::Demo::TemperatureConverter', facetOrContext, context)

        @staticmethod
        def uncheckedCast(proxy, facet=None):
            return _M_Demo.TemperatureConverterPrx.ice_uncheckedCast(proxy, facet)

        @staticmethod
        def ice_staticId():
            return '::Demo::TemperatureConverter'

    _M_Demo._t_TemperatureConverterPrx = IcePy.defineProxy('::Demo::TemperatureConverter', TemperatureConverterPrx)
    _M_Demo.TemperatureConverterPrx = TemperatureConverterPrx
    del TemperatureConverterPrx

    _M_Demo.TemperatureConverter = Ice.createTempClass()
    class TemperatureConverter(Ice.Object):

        def ice_ids(self, current=None):
            return ('::Demo::TemperatureConverter', '::Ice::Object')

        def ice_id(self, current=None):
            return '::Demo::TemperatureConverter'

        @staticmethod
        def ice_staticId():
            return '::Demo::TemperatureConverter'

        def celsiusToFahrenheit(self, celsius, current=None):
            raise NotImplementedError("servant method 'celsiusToFahrenheit' not implemented")

        def fahrenheitToCelsius(self, fahrenheit, current=None):
            raise NotImplementedError("servant method 'fahrenheitToCelsius' not implemented")

        def celsiusToKelvin(self, celsius, current=None):
            raise NotImplementedError("servant method 'celsiusToKelvin' not implemented")

        def __str__(self):
            return IcePy.stringify(self, _M_Demo._t_TemperatureConverterDisp)

        __repr__ = __str__

    _M_Demo._t_TemperatureConverterDisp = IcePy.defineClass('::Demo::TemperatureConverter', TemperatureConverter, (), None, ())
    TemperatureConverter._ice_type = _M_Demo._t_TemperatureConverterDisp

    TemperatureConverter._op_celsiusToFahrenheit = IcePy.Operation('celsiusToFahrenheit', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_float, False, 0),), (), ((), IcePy._t_float, False, 0), ())
    TemperatureConverter._op_fahrenheitToCelsius = IcePy.Operation('fahrenheitToCelsius', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_float, False, 0),), (), ((), IcePy._t_float, False, 0), ())
    TemperatureConverter._op_celsiusToKelvin = IcePy.Operation('celsiusToKelvin', Ice.OperationMode.Normal, Ice.OperationMode.Normal, False, None, (), (((), IcePy._t_float, False, 0),), (), ((), IcePy._t_float, False, 0), ())

    _M_Demo.TemperatureConverter = TemperatureConverter
    del TemperatureConverter

# End of module Demo
